### ISSUE TITLE
Dynamic exception specification deprecated in C++11

### ISSUE THREAD

**Issue by zhxchen17** [cmu-db/peloton#876]
When trying to build Peloton with some newer version of gcc (e.g. 7.2.0), I encountered errors like the following:
```
/peloton/src/common/allocator.cpp:41:33: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 void *operator new(size_t size) throw(std::bad_alloc) {
                                 ^~~~~
/peloton/src/common/allocator.cpp:49:35: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 void *operator new[](size_t size) throw(std::bad_alloc) {
                                   ^~~~~
```
It seems that it is not a big issue, but it would be nice to migrate to the up-to-date practice in C++ community, as advised at http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0003r0.html#5.0, which originally proposed to deprecate the Exception Specification feature from C++11.

If this seems reasonable, I would like to follow the guides at https://github.com/cmu-db/peloton/blob/master/CONTRIBUTING.md and send a PR fixing this.

**Comment by apavlo** [comment]
@zhxchen17 If you can send us a PR with this, we would definitely be interested. I suspect that is not the only error that you are going to hit with newer versions of gcc.

**Comment by zhxchen17** [comment]
@apavlo Sure, looks like a good start point. May add some other compiler minor issues in the following part of the thread.

**Comment by MalcolmUnWang** [comment]
@apavlo @zhxchen17 This error also happens to me, along with many other errors, when I upgraded my Ubuntu to 17.10. It upgraded the `gcc-5.4.0` to `gcc-7.1.0`. The error is a warning actually and can remove by modifying `CMakeList.txt` to disable `-Werror`. However, there are numerous other compiler errors which will happen on this specific release of Ubuntu. The `protobuf` version will be `3.0.0` which has a bug during compiling, `llvm-3.7` is not supported in `Ubuntu 17.10` and `llvm` with other versions will all result in errors, etc. I think maybe we can modify `Installation` part of `wiki` a little bit to tell beginners not to use `Ubuntu 17.10`. 
And I also found that `Windows Subsystem for Linux` can compile `peloton` pretty well, but when `peloton` is running it cannot produce any result after `listening on port [number]`. That's because WSL does not implement Unix socket. Excluding WSL for beginners to install `peloton` explicitly might be helpful, too, I think.

**Comment by apavlo** [comment]
> The error is a warning actually and can be removed by modifying CMakeList.txt to disable -Werror

Do **not** do this.

>  I think maybe we can modify Installation part of wiki a little bit to tell beginners not to use Ubuntu 17.10

You can use Ubuntu 17.10, you just have to downgrade gcc.

We will fix the llvm upgrade issues later this month.

> And I also found that Windows Subsystem for Linux can compile peloton pretty well, but when peloton is running it cannot produce any result after listening on port [number]. That's because WSL does not implement Unix socket. Excluding WSL for beginners to install peloton explicitly might be helpful, too, I think.

We don't care about Windows at this point.

**Comment by zhxchen17** [comment]
> You can use Ubuntu 17.10, you just have to downgrade gcc.

Agree. 
I guess for now it would be nice to just do forward compatibility with gcc-7, but keep gcc-5 as the default compiler. I'm working on this, and actually get a working build with 7.2, but still investigating some subtle errors in the unit test. (Basically I do not know whether it is caused by my tweaks or by my machine.)
As WSL user myself, I would say it is still in beta and lots of stuff are broken. I think it's better to focus on Unix builds first.

**Comment by poojanilangekar** [comment]
Closing this issue since the build works on gcc-4.8.
