### ISSUE TITLE
Linker errors with libjsconcpp v1.7 on Ubuntu 16.04

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#193]
I was able to get the source code compile with gcc 5.3.1 but there is a linker error due to a problem with `libjson-cpp` v1.7:

```
[100%] Linking CXX executable ../bin/peloton
../lib/libpeloton-d.so.0.0.3: undefined reference to `Json::Value::operator=(Json::Value const&)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/peloton-bin.dir/build.make:107: recipe for target 'bin/peloton' failed
make[2]: *** [bin/peloton] Error 1
CMakeFiles/Makefile2:1088: recipe for target 'src/CMakeFiles/peloton-bin.dir/all' failed
make[1]: *** [src/CMakeFiles/peloton-bin.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
````

Apparently this is a known problem with v1.7. They fixed in v1.8:

http://stackoverflow.com/a/28570134

Ubuntu is not going to switch to the new version in the next release. So we may want to include it as a third-party dependency. It's MIT licensed.

**Comment by jarulraj** [comment]
Removed `jsoncpp` dependency.
