### ISSUE TITLE
New parser doesn't compile on flex 2.6

### ISSUE THREAD

**Issue by apavlo** [cmu-db/peloton#198]
flex: 2.6.0
bison: 3.0.4
gcc: 5.4.0

```
pavlo@tiberius:~/Documents/Peloton/Github/peloton/build$ make
[  2%] Built target peloton-proto
Scanning dependencies of target peloton-parser
[  2%] [BISON][SQLParser] Building parser with bison 3.0.4
[  2%] Building CXX object src/CMakeFiles/peloton-parser.dir/sql_parser.cpp.o
[  4%] Building CXX object src/CMakeFiles/peloton-parser.dir/sql_scanner.cpp.o
/home/pavlo/Documents/Peloton/Github/peloton/build/src/sql_scanner.cpp: In function ‘int yy_get_next_buffer(yyscan_t)’:
/home/pavlo/Documents/Peloton/Github/peloton/build/src/sql_scanner.cpp:3447:47: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  if ((int) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
                                               ^
cc1plus: all warnings being treated as errors
src/CMakeFiles/peloton-parser.dir/build.make:98: recipe for target 'src/CMakeFiles/peloton-parser.dir/sql_scanner.cpp.o' failed
make[2]: *** [src/CMakeFiles/peloton-parser.dir/sql_scanner.cpp.o] Error 1
CMakeFiles/Makefile2:1197: recipe for target 'src/CMakeFiles/peloton-parser.dir/all' failed
make[1]: *** [src/CMakeFiles/peloton-parser.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

The C++ code is easy to fix, but obviously we have to do this every time . This is a one-liner fix:

`sed -i 's/ > YY_CURRENT_BUFFER_LVALUE/ > (int)YY_CURRENT_BUFFER_LVALUE/g' src/sql_scanner.cpp`

Newer versions of flex should not have this problem.

**Comment by wangziqi2016** [comment]
I have seen this problem on Kubuntu with flex 2.6.0

But after downgrading to flex 2.5.35 (copying the binary from any of the dev machine suffices) this problem no longer appears.

**Comment by jarulraj** [comment]
Added `-Wno-sign-compare` to parser compilation flags. This should fix this issue.
