### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by zagnix** [cmu-db/peloton#767]
ERROR：
[100%] Linking CXX executable ../bin/peloton
../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::RuntimeDyld::MemoryManager'
../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::SectionMemoryManager'
../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::CmpInst'
../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::Instruction'
../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::UnaryInstruction

llvm version ?

**Comment by apavlo** [comment]
Platform? Compiler version?

**Comment by apavlo** [comment]
@zagnix Can you provide more information?

**Comment by zagnix** [comment]
@apavlo

-- ******************* Peloton Configuration Summary *******************
-- General:
--   Version           :   0.0.5
--   Git               :   7286f58
--   System            :   Linux
--   Compiler          :   /usr/bin/c++ (gcc 4.8.5)
--   Release CXX flags :   -O3 -DNDEBUG -std=c++1y -D__PELOTONFILE__='"$(subst /root/peloton/peloton/,,$(abspath $<))"' -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-strict-aliasing
--   Debug CXX flags   :   -g -O0 -ggdb -fno-omit-frame-pointer -fno-optimize-sibling-calls -std=c++1y -D__PELOTONFILE__='"$(subst /root/peloton/peloton/,,$(abspath $<))"' -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-strict-aliasing
--   Build type        :   Release
-- 
--   BUILD_docs        :   ON
-- 
-- Dependencies:
--   Linker flags      :   
--   Boost             :   Yes (ver. 1.59)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.1.0)
--   LLVM              :   Yes (ver. 3.7.0)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.5)
--   config_file       :   
-- 
-- Install:
--   Install path      :   /root/peloton/peloton/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/peloton/peloton/build

**Comment by zagnix** [comment]
@apavlo thks  

cmake -DCMAKE_BUILD_TYPE=Release ../


 General:
   Version           :   0.0.5
   Git               :   7286f58
   System            :   Linux
   Compiler          :   /usr/bin/c++ (gcc 4.8.5)
   Release CXX flags :   -O3 -DNDEBUG -std=c++1y -D__PELOTONFILE__='"$(subst /root/peloton/peloton/,,$(abspath $<))"' -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-strict-aliasing
   Debug CXX flags   :   -g -O0 -ggdb -fno-omit-frame-pointer -fno-optimize-sibling-calls -std=c++1y -D__PELOTONFILE__='"$(subst /root/peloton/peloton/,,$(abspath $<))"' -fPIC -Wall -Wextra -Werror -mcx16 -Wno-invalid-offsetof -march=native -Wno-strict-aliasing
   Build type        :   Release
    BUILD_docs        :   ON
 
 Dependencies:
   Linker flags      :   
   Boost             :   Yes (ver. 1.59)
   glog              :   Yes
   gflags            :   Yes
   protobuf          :   Yes (ver. 3.1.0)
  LLVM              :   Yes (ver. 3.7.0)
 
 Documentaion:
   Doxygen           :   /usr/bin/doxygen (1.8.5)
   config_file       :   
 
 Install:
   Install path      :   /root/peloton/peloton/build/install
 
 Configuring done
 Generating done
 Build files have been written to: /root/peloton/peloton/build

make

**Comment by pmenon** [comment]
You need to use a newer compiler, at least GCC 4.9.  

The problem is related to an ABI change between GCC 4.8 and GCC 4.9+ w.r.t. strings ([here](https://stackoverflow.com/questions/30124264/undefined-reference-to-googleprotobufinternalempty-string-abicxx11)). The Libprotobuf and LLVM libraries on the machine are compiled with GCC 4.9+, which cannot linked with apps compiled with anything older than 4.9. We should settle on GCC 4.9 as the oldest compiler we support. We use it in our tests, and it has the minimum set of C++11 features we need.

**Comment by crd477** [comment]
The Ubuntu 14.04 build works using `gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)` assuming all of the other dependencies are installed from the official Ubuntu repositories, except for LLVM-3.7 which I noticed **must** be installed from the apt.llvm.org repository.

**Comment by fzhedu** [comment]
> ERROR：
> [100%] Linking CXX executable ../bin/peloton
> ../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::RuntimeDyld::MemoryManager' ../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::SectionMemoryManager'
> ../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::CmpInst' ../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::Instruction'
> ../lib/libpeloton.so.0.0.5: undefined reference to `typeinfo for llvm::UnaryInstruction
> 
> llvm version ?

@zagnix

Did you solve this problem? I face this problem now.
system : CENTOS 7
-- ******************* Peloton Configuration Summary *******************
-- General:
--   Version           :   0.0.5
--   Git               :   484d76d-dirty
--   System            :   Linux
--   Compiler          :   /home/claims/Downloads/gcc-build-6.4.0/install/bin/c++ (gcc 6.4.0)
--   Release CXX flags :   -O3 -DNDEBUG -std=c++11 -Wno-c++14-compat -D__PELOTONFILE__='"$(subst /home/claims/Documents/peloton/,,$(abspath $<))"' -fdiagnostics-color=auto -fPIC -mcx16 -march=native -Wall -frtti -Wextra -Wno-error -Wno-invalid-offsetof -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wno-strict-aliasing
--   Debug CXX flags   :   -g -O0 -ggdb -fno-omit-frame-pointer -fno-optimize-sibling-calls -std=c++11 -Wno-c++14-compat -D__PELOTONFILE__='"$(subst /home/claims/Documents/peloton/,,$(abspath $<))"' -fdiagnostics-color=auto -fPIC -mcx16 -march=native -Wall -frtti -Wextra -Wno-error -Wno-invalid-offsetof -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wno-strict-aliasing
--   Build type        :   Release
-- 
--   BUILD_docs        :   ON
-- 
-- Dependencies:
--   Linker flags      :    -fuse-ld=gold -Wl,--disable-new-dtags
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.5.1)
--   capnproto         :   No
--   LLVM              :   Yes (ver. 3.7.0)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.5)
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/claims/Documents/peloton/build/install
-- 
-- Configuring done
